name: CI

on:
  # push:
  #   branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Runs Git-Actions
        uses: actions/checkout@v4
      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pytest
        run: pip install pytest flask-testing
      
      - name: Run Unit test     
        run: pytest      
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Image (dont push)
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:1.0.0
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ secrets.DOCKERHUB_USERNAME }}/flask-app:1.0.0'

      - name: Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/flask-app:1.0.0
